/** Short, readable examples for the interactive syntax preview. */
export const syntaxSamples: Record<string, Array<[string, string]>> = {
    typescript: [['comment', '// A small palette, a clear intent.\n'], ['keyword', 'export interface '], ['type', 'Theme'], ['text', ' {\n  '], ['property', 'name'], ['operator', ': '], ['type', 'string'], ['text', ';\n  '], ['property', 'radius'], ['operator', ': '], ['type', 'number'], ['text', ';\n}\n\n'], ['keyword', 'const '], ['variable', 'theme'], ['operator', ': '], ['type', 'Theme'], ['operator', ' = '], ['text', '{ '], ['property', 'name'], ['operator', ': '], ['string', '"Nitro"'], ['text', ', '], ['property', 'radius'], ['operator', ': '], ['number', '12'], ['text', ' };\n'], ['keyword', 'function '], ['function', 'describe'], ['text', '('], ['parameter', 'theme'], ['operator', ': '], ['type', 'Theme'], ['text', ') {\n  '], ['keyword', 'return '], ['parameter', 'theme'], ['text', '.'], ['property', 'name'], ['text', ';\n}\n'], ['function', 'describe'], ['text', '('], ['variable', 'theme'], ['text', ');']],
    python: [['comment', '# Comfortable colors for everyday code.\n'], ['keyword', 'from '], ['type', 'dataclasses'], ['keyword', ' import '], ['function', 'dataclass'], ['text', '\n\n'], ['function', '@dataclass'], ['text', '\n'], ['keyword', 'class '], ['type', 'Theme'], ['text', ':\n    '], ['property', 'name'], ['text', ': '], ['type', 'str'], ['text', '\n    '], ['property', 'radius'], ['text', ': '], ['type', 'int'], ['operator', ' = '], ['number', '12'], ['text', '\n\n'], ['keyword', 'def '], ['function', 'describe'], ['text', '('], ['parameter', 'theme'], ['text', ': '], ['type', 'Theme'], ['text', ') -> '], ['type', 'str'], ['text', ':\n    '], ['keyword', 'return '], ['parameter', 'theme'], ['text', '.'], ['property', 'name'], ['text', '\n\n'], ['variable', 'theme'], ['operator', ' = '], ['type', 'Theme'], ['text', '('], ['string', '"Nitro"'], ['text', ')\n'], ['function', 'print'], ['text', '('], ['function', 'describe'], ['text', '('], ['variable', 'theme'], ['text', '))']],
    dart: [['keyword', 'class '], ['type', 'Theme'], ['text', ' {\n  '], ['keyword', 'final '], ['type', 'String '], ['property', 'name'], ['text', ';\n  '], ['keyword', 'final '], ['type', 'int '], ['property', 'radius'], ['text', ';\n\n  '], ['keyword', 'const '], ['type', 'Theme'], ['text', '('], ['keyword', 'this'], ['text', '.'], ['property', 'name'], ['text', ', {'], ['keyword', 'this'], ['text', '.'], ['property', 'radius'], ['operator', ' = '], ['number', '12'], ['text', '});\n}\n\n'], ['type', 'void '], ['function', 'main'], ['text', '() {\n  '], ['keyword', 'const '], ['variable', 'theme'], ['operator', ' = '], ['type', 'Theme'], ['text', '('], ['string', "'Nitro'"], ['text', ');\n  '], ['function', 'print'], ['text', '('], ['variable', 'theme'], ['text', '.'], ['property', 'name'], ['text', ');\n}']],
    markdown: [['heading', '# Gradient Nitro\n\n'], ['text', 'A colorful workspace with '], ['keyword', '**clear hierarchy**'], ['text', '.\n\n'], ['heading', '## Quick start\n\n'], ['type', '- '], ['text', 'Choose dark or light mode.\n'], ['type', '- '], ['text', 'Make the palette your own.\n\n'], ['string', '`const radius = 12;`'], ['text', '\n\n'], ['link', '[Open the guide](https://example.com/guide)'], ['text', '\n\n'], ['type', '> '], ['text', 'Keep the code in focus.']],
    dotenv: [['comment', '# Example values only — no credentials\n'], ['keyword', 'export '], ['property', 'APP_NAME'], ['operator', '='], ['string', '"Gradient Nitro"'], ['text', '\n'], ['property', 'PORT'], ['operator', '='], ['number', '3000'], ['text', '\n'], ['property', 'DEBUG'], ['operator', '='], ['constant', 'true'], ['text', '\n'], ['property', 'API_URL'], ['operator', '='], ['string', '"https://example.com"'], ['text', '\n'], ['property', 'CACHE_DIR'], ['operator', '='], ['variable', '${HOME}'], ['string', '/.cache/nitro'], ['text', '\n']],
    plaintext: [['heading', '# Release notes\n\n'], ['keyword', 'DONE'], ['text', '  Rounded workspace components\n'], ['keyword', 'DONE'], ['text', '  Language-aware syntax colors\n'], ['keyword', 'TODO'], ['text', '  Review the next palette\n\nVersion: '], ['number', '1.2.0'], ['text', '\nPreview: '], ['link', 'https://example.com/preview'], ['text', '\nContact: '], ['link', 'hello@example.com'], ['text', '\n']]
};
